server:
  port: 8080
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:attornatus_database
    username: root
    password: root

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
